appirio-tech/accounts-app

app/app-config.coffee, app/scripts/logout.controller.coffee, core/token.js
- Show message from Zendesk
- Fixed Cookie name in Logout code
=> Zendesk SSO

app/scripts/tc/login.controller.coffee
Fixed the issue: Can't SSO when session is expired in Zendesk
=> Promoting to Production

app/scripts/login.controller.coffee, app/scripts/tc/login.controller.coffee, core/auth.js, core/constants.js, core/token.js
Task: [accounts.topcoder.com does not pass v2 cookies to applications](https://app.asana.com/0/100297043256537/113052831211870)
Task: [Can't SSO when session is expired in Zendesk](https://app.asana.com/0/99116749388887/109952311995178)
=> V2 tokens support

app/views/tc/register.jade
-- Fixed login link on registration page for members app
=> AS#100297043256582, Move all login to link of Members to accounts.topcoder.com

app/scripts/tc/reset-password.controller.js
=> AS#141874817806575, Reset password not working

app/scripts/directives/validate-email.directive.js
=> AS#141874817806562, Member Reg: email address validation not showing message

app/styles/tc/account.scss
=> AS#141874817806555, Footer is misaligned on Member Login page

app/index.jade
-- Replaced kit which allows qa and production domains as well
=> AS#140552732636493, Fix styling on Connect Login page

app/scripts/connect/registration.controller.coffee
-- Fixed, defaulted after activation url to connect.topcoder.com
@parthshah do you see any issue with this change?
=> AS#142925337186043, Fix incorrect activation url for connect user registration

app/views/tc/register.jade
-- Removed success bar from fields to avoid distraction for user
@fnisen @parthshah fyi
=> AS#141874817806568, Member Reg: password form styling

app/app-run.coffee, app/index.jade, app/scripts/footer.controller.coffee
-- hide footer while state is loading
=> AS#140552732636486, Remove interstitial page before Login page loads

core/token.js
-- Fixed issue with legacy cookies (tcjwt, tcsso) which are set at the root domain level
@ajefts @fnisen @parthshah @mdesiderio fyi
=> AS#118482918232213, Bug : While logging in/out from www.topcoder-dev.com/direct

app/styles/connect/main.scss, app/styles/tc/topcoder.scss, app/views/connect/login.jade, app/views/connect/registration.jade
-- Fixed text for login link
-- Fixed position of footer
-- Fixed background color of the footer
fyi, @fnisen @vic-appirio @parthshah
=> Fix styling on Connect Registration page

app/styles/connect/forgot.scss, app/styles/connect/login-reg-shell.scss, app/styles/connect/login.scss, app/styles/connect/main.scss, app/styles/connect/registration.scss, app/styles/connect/reset.scss, app/views/connect/forgot-password.jade, app/views/connect/login.jade, app/views/connect/registration.jade, app/views/connect/reset-password.jade, app/views/connect/sso-login.jade
-- Fixed mobile layout for the login page of connect
-- Mobile layout fixes for registration page
-- Mobile layout fixes for forgot-password and reset-password pages
-- Fixed wrong login link on reset password page for connect
-- Fixed locked height for sos login page
=> Fix styling(mobile layout) on Connect Registration and Login pages

connector/connector-embed.js
-- Potential fix. It seems like it was happening only for Google chrome users.
@parthshah instead of hotfix I have created normal feature branch so that I can test it out on dev first.
=> AS#153276200846784, Blank screens on production after accounts app integration deployment

app/scripts/tc/register.controller.js
@ajefts @fnisen @parthshah fyi
We need to get this on production as soon as we can do so that we don't loose UTM params for new registrations.
=> Promoting changes to QA (Registration UTM params, Blank Screen potential fix)

app/scripts/tc/login.controller.coffee
=> AS#153916199594946, Log in form does reset after incorrect username

app/scripts/connect/registration.controller.coffee, app/styles/connect/login-reg-shell.scss, app/views/connect/registration.jade
-- Added country field to connect reg form
-- Removed organization field
=> AS#156182574694098, Add country field to Connect registration form

core/auth.js, core/constants.js
-- Updated social extraction method to get access token and secret from user api instead of original auth0 token
-- Exported the extractSocialData method to reuse it in topcoder-app as well for external account linking
@parthshah @ajefts @fnisen I am creating the PR for Auth0 migration changes. And once this PR is merged we need to be careful in production deployment of topcoder-app and work-app because they both are pointing to the dev branch. Hence, if in any way we deploy the topcoder-app/work-app after merging this PR, it may cause errors in external account linking and social registration use cases. Solution to that would be either merge the [auth0 migration branch](https://github.com/appirio-tech/topcoder-app/tree/feature/auth0-idp-migratino) into dev/qa/master and then deploy the …
=> AS#163129582694726, Auth0 migration "Identity Provider access tokens removed from user profile and id_token"

package.json
Reverts appirio-tech/accounts-app#63
fyi @parthshah
=> Revert "AS#163129582694726, Auth0 migration "Identity Provider access tokens …"

core/auth.js, core/constants.js
Reverts appirio-tech/accounts-app#62
=> Revert "AS#163129582694726, Auth0 migration "Identity Provider access tokens removed from user profile and id_token""

app/scripts/tc/register.controller.js, core/token.js
This PR contains:
- updating isLoggedIn() to check if all required tokens are set. (https://github.com/appirio-tech/accounts-app/commit/e0fa8b7828646f8ac927e843d083d815acdc26b7)
- Adding # of days to keep cookie valid (https://github.com/appirio-tech/accounts-app/pull/69/commits/a6562493d649b764df8322ad2ef498800c19701b)
- added auth0UserId to context param (https://github.com/appirio-tech/accounts-app/pull/69/commits/1ee5b59477bfc31f9c0d0dfcaf4165eccf3b66d2)
=> Promoting to QA

app/scripts/tc/register.controller.js, connector/connector-embed.js, connector/connector-wrapper.js, core/constants.js
=> Promoting PR#71 to QA

core/utils.js
Related task: [Remove Auth0 LDAP Connector](https://app.asana.com/0/100297043256605/238517801337836)
=> Don't use LDAP when logging in with handle

core/auth.js
https://github.com/appirio-tech/accounts-app/pull/81
=> Promoting PR#81 to QA

core/utils.js
PR#81 Don't use LDAP when logging in with handle
=> Promoting PR#81 to Production

app/scripts/connect/sso-login.controller.coffee, core/auth.js, core/constants.js, core/token.js, package.json
Accounts app was redirecting to Auth0 auth API with a wrong callback URL.
[x] https://api.topcoder-dev.com/v3/pub/callback.html
[o] https://api.topcoder-dev.com/pub/callback.html
And the callback URL to SSO login also needed the following fix:
[x] https://accounts.topcoder-dev.com/sso-callback
[o] https://accounts.topcoder-dev.com/#!/sso-callback
* This might be caused by the changes in S3 configuration.
=> Hotfix for SSO callback issue

app/scripts/tc/reset-password.controller.js, app/views/tc/reset-password.jade
GET /v3/users/resetToken
- returns 403 Forbidden for users associated with SSO account
=> Error handling for 403 from resetToken API

app/app-config.coffee, app/scripts/connect/sso-callback.controller.coffee, core/auth.js
https://api.topcoder.com/pub/callback.html feeds jwt and refresh tokens from Auth0 on the following parameters:
- auth0Jwt
- auth0Refresh
=> SSO/Social callbacks receive Auth0 tokens

.travis.yml, app/app-run.coffee, app/index.jade, app/views/segment.io.jade, core/constants.js
=> Add segment.io to this branch that we're pushing to dev for some reason

app/app-run.coffee, app/index.jade, app/views/segment.io.jade
@mtwomey @ajefts - tonight's login issue temporary hotfix.
=> Production login issuefix 20170621

app/app-config.coffee, app/scripts/connect/registration.controller.coffee, app/scripts/tc/register.controller.js, app/views/connect/registration-success.jade, app/views/tc/registered-successfully.jade
=> Promoting PR#115 to Production

app/app-config.coffee, app/scripts/tc/register.controller.js, connector/connector-wrapper.js, npm-shrinkwrap.json
This still needs some cleanup, but urgent right now.
=> Add deep link for registration (for Wipro)

app/views/tc/register.jade
=> Hide social sso

app/views/tc/register.jade
Reverts appirio-tech/accounts-app#126
=> Revert "adding ng-show to false for sso"

app/views/tc/register.jade
Reverts appirio-tech/accounts-app#125
=> Revert "Hide social sso"

app/app-config.coffee, app/scripts/directives/sso-registration.directive.js, app/scripts/tc/register.controller.js, app/styles/connect/login-reg-shell.scss, app/styles/tc/account.scss, app/views/tc/register.jade, core/auth.js, core/constants.js
fyi @ajefts @dmessing @mtwomey
=> Hotfix containing multiple fixes for SSO related issues

app/app-config.coffee, app/scripts/tc/register.controller.js
URL update to have trailing /
Better error handling for already registered SSO user
=> SSO registration related hotfixes

.travis.yml, app/scripts/tc/register.controller.js, core/auth.js
This merge into dev should deploy the application to the new bucket accounts-test.topcoder-dev.com
=> Fixing same message issue for sso and non sso users

.travis.yml, app/app-config.coffee, app/scripts/tc/register.controller.js, app/scripts/tc/registration-success.controller.js, app/views/tc/registered-successfully.jade, core/auth.js
#133 , Same message being shown for sso and non sso users …
#134, Provide return URL link in the registration success message for SSO users
=> Fixes to registration success page

app/views/connect/registration.jade, app/views/tc/register.jade
— Made email field readonly for sso users
fyi, @ajefts
=> Github issue#124, Go straight to SSO registration

app/app-run.coffee, app/index.jade
Issue
https://github.com/appirio-tech/connect-app/issues/1047
Commits
https://github.com/appirio-tech/accounts-app/commit/47662b3e94f6645df040b67b4b74df3a869d4690#diff-142c10d0a6d201fe205ceb9d6ae8890a
https://github.com/appirio-tech/accounts-app/commit/d02d1f03898c9c444a50042b0569fc0644c0374f#diff-142c10d0a6d201fe205ceb9d6ae8890a
=> Revert hide banner changes

app/scripts/connect/registration.controller.coffee, app/views/connect/registration.jade
https://github.com/appirio-tech/connect-app/issues/980#issuecomment-319546243
=> Update error message and Styling

app/views/connect/pin-verification.jade, app/views/connect/registration.jade
— Converted the page heading to information message (green boxes)
=> Github issue#960, Update copy for new connect register flow in logged out project creation flow

core/auth.js
— Handled ‘Failed to fetch” error to show generic error message.
=> Github issue#980, Can't create a new account "Unexpected end of JSON input" error displayed

app/scripts/tc/reset-password.controller.js
=> Github issue#961, Reset Password malfunctioning in prod (on member side)

app/styles/tc/reset-password.scss
=> Github issue#164, Show password button is misplaced on member side reset password page

app/scripts/connect/pin-registration.controller.coffee, app/views/connect/pin-verification.jade
After 10 errors, another message is displayed and it is no longer possible to verify the PIN.
=> #1059 Error message is not displayed if user enters wrong PIN so many times

app/views/connect/forgot-password.jade, app/views/connect/login.jade, app/views/connect/pin-verification.jade, app/views/connect/registration-success.jade, app/views/connect/registration.jade, app/views/connect/reset-password.jade
issue of connect copyright fixed
https://github.com/appirio-tech/connect-app/issues/1756
@gondzo please check
=> issue 1756 fix for connect

app/scripts/connect/login.controller.coffee
=> final fix challenge 30070946

app/scripts/connect/registration.controller.coffee, app/scripts/connect/welcome.coffee, core/auth.js
1. Save the new user info (Business Phone, Title, Company Name, and Company Size) - we’ll need call the new traits API to add the business information Postman here: https://www.getpostman.com/collections/9d74c856e4a79510af01 This has to be done after the registration calls because it uses the TC username
2. Return back to connect when clicking the select your solution button. redirect to  CONNECT_URL/new-project route
3. In connect app remove unauthenticated project creation flow from routes, so that it now always requires users to login before creating project
4. In connect-app update CreateContainer and its child components to include the new left and right panel in the project creation wizard
5. In connect app add new step in the project wizard for showing the `Project Submitted` step …
=> finish left steps in registration/login flow

core/auth.js
instead of only removing the error checking as pointed by @maxceem, it is still satisfying the conditions for the issue.
=> Removed the change completely

app/scripts/connect/registration.controller.coffee
=> Patch release to fix missing businessPhone in lead info

package.json
=> Switched Account-App back to connectv2 branch

app/scripts/connect/registration.controller.coffee, core/auth.js, core/constants.js, package.json
This release contains the following changes - 
1.Renaming of trait for connect
2.Updating react-components dependency
3.SSO for Zurich test accounts
After this PR is merged to master, we have to manually run an update script to rename older trait 'customer_info' to 'connect-info'
fyi @vikasrohit @mtwomey
=> PROD Release

app/app-config.coffee, app/scripts/connect/pin-registration.controller.coffee, app/scripts/connect/registration.controller.coffee, core/auth.js, core/constants.js, package.json
=> Supporting Release for Connect 2.4.8

app/scripts/connect/login.controller.coffee, app/scripts/connect/registration.controller.coffee
SSO login/registration support for Connect flows
=> Support for SSO user in Connect flows

connector/connector-embed.js, core/utils.js
This will check the naked domain.
So, you'll just have to allow a domain like `topcoder.com` and any `*.topcoder.com/**/**` will be valid.
=> Fix security issue with allowed origins

app/views/tc/login.jade
https://github.com/topcoder-platform/community-app/issues/2815 fixes
=> issue 2815 fix

app/views/tc/reset-password.jade
fixes topcoder-platform/community-app#2906
=> Issue 2906 fix

app/styles/directives/toggle-password.directive.scss
https://github.com/topcoder-platform/community-app/issues/2767
=> issue 2767 fix

app/styles/tc/login.scss
https://github.com/topcoder-platform/community-app/issues/2768
=> issue 2768 fix

app/views/tc/register.jade
Added tabindex = 0 to country field, because otherwise adding non zero tabindex will skip the field
=> MSFT 45 Issue#2766

app/styles/tc/account.scss, app/views/tc/login.jade, app/views/tc/register.jade
fixes topcoder-platform/community-app#2738
=> Issue 2738 fix

app/styles/tc-ui-variables.scss, app/styles/tc/register.scss
Reverts appirio-tech/accounts-app#242
=> Revert "Issue 2775 fix"

app/styles/tc/login.scss
Reverts appirio-tech/accounts-app#229
=> Revert "issue 2768 fix"

app/styles/tc/account.scss
fixes https://github.com/topcoder-platform/community-app/issues/2883
=> issue 2883 fix

app/styles/connect/login.scss, app/styles/tc/account.scss, app/styles/tc/register.scss
Fix for https://github.com/topcoder-platform/community-app/issues/2859
=> fix for #2859

app/app-config.coffee, app/app-run.coffee, app/index.jade
https://github.com/topcoder-platform/community-app/issues/2771  
MSFT-54 Fix page title.  
Set up the base for specifying individual title for other pages when needed in future.
=> Fix for Community App Issue #2771 MSFT-54 Page Title

app/index.jade
Issue https://github.com/topcoder-platform/community-app/issues/2783
=> MSFT-69-Issue#2783 - added lang attribute to html

app/index.jade, app/views/tc/register.jade
https://github.com/topcoder-platform/community-app/issues/2866
=> Register page region.

app/styles/tc/account.scss, app/views/tc/login.jade
fixes topcoder-platform/community-app#2738
=> Issue 2738 fix - add title on img

app/styles/tc/login.scss
Reverts appirio-tech/accounts-app#273
=> Revert "Issue 2768  fix"

app/styles/tc/reset-password.scss, app/views/tc/login.jade, app/views/tc/reset-password.jade
Added some aria-labels in forgot password and back to login links
Back to login is now highlighted when focus.
https://github.com/topcoder-platform/community-app/issues/2880
=> Fix issue #2880

app/views/tc/register.jade
To replace 
https://github.com/appirio-tech/accounts-app/pull/274
Related with issue
topcoder-platform/community-app#2866
=> Registration form aria-label

app/styles/directives/toggle-password-with-tips.directive.scss, app/styles/tc-ui.scss, app/styles/tc/register.scss, app/views/directives/toggle-password-with-tips.directive.jade, app/views/tc/register.jade
=> Merge PRs #248 and #278

app/scripts/directives/toggle-password-directive-tips.js, app/scripts/tc/register.controller.js, app/views/directives/toggle-password-with-tips.directive.jade, app/views/tc/register.jade
https://github.com/topcoder-platform/community-app/issues/2813
https://github.com/topcoder-platform/community-app/issues/2827
=> Register username, email, password tooltip.

app/styles/tc/register.scss
Fix for https://github.com/topcoder-platform/community-app/issues/2859
=> Fix 'terms' link underline

app/styles/tc/register.scss
Changes for https://github.com/topcoder-platform/community-app/issues/3240
=> Fix contrast | Issue #3240

app/styles/directives/toggle-password.directive.scss, app/styles/tc/login.scss, app/views/directives/toggle-password.directive.jade, app/views/tc/login.jade
Changes for https://github.com/topcoder-platform/community-app/issues/3232
=> Issue 3232 | Add labels

app/styles/tc/register.scss, app/views/tc/register.jade
Changes for https://github.com/topcoder-platform/community-app/issues/3236
=> Issue 3236| Add form labels

app/index.jade, app/styles/tc/account.scss, app/views/tc/login.jade, app/views/tc/register.jade
Changes for https://github.com/topcoder-platform/community-app/issues/3234
=> Issue 3234 | Add landmarks

app/views/directives/toggle-password.directive.jade, app/views/tc/login.jade, npm-shrinkwrap.json, package.json
Upgrade version of react-components
=> Supporting release for Connect 2.4.14 

core/auth.js, core/constants.js
Reverts appirio-tech/accounts-app#314
=> Revert "Kill Direct-app session on logout"

app/scripts/connect/registration.controller.coffee, npm-shrinkwrap.json, package.json
=> [Master][Patch]Hotfix/forward optin flag to sf

app/scripts/connect/registration.controller.coffee
Fix issue: https://github.com/appirio-tech/connect-app/issues/3359
=> add timezone in registration page

app/scripts/connect/registration.controller.coffee
To pass along the topcoder user id of the lead
=> Passed UserId to the creatLead endpoint

npm-shrinkwrap.json, package.json
Change to burst circle-ci cache during deployment.
fyi @vikasrohit
=> Cache burst Change

.circleci/config.yml
@sachin-maheshwari @Gunasekar-K Please review and merge.
fyi @mtwomey
=> Updated checksum key to shrinkwrap

npm-shrinkwrap.json, package.json
Fix some alpha2 country codes, but I didn't check if the rest of codes are correct.
ref issues appirio-tech/connect-app#3819 and appirio-tech/ng-iso-constants#10
=> [HOTFIX] [DEV] alpha2 country codes

.circleci/config.yml
Reverts appirio-tech/accounts-app#334
=> Revert "Updated checksum key to shrinkwrap"

npm-shrinkwrap.json, package.json
Fix some alpha2 country codes, but I didn't check if the rest of codes are correct.
ref issues appirio-tech/connect-app#3819 and appirio-tech/ng-iso-constants#10
=> [HOTFIX] [PROD] alpha2 country codes 

npm-shrinkwrap.json, package.json
Allowing topcoder.com domain for wipro SSO login.
=> SSO (wipro-adfs) topcoder.com domain issue
